CREATE TABLE Sheet1(--_========================================== VARCHAR(10));
INSERT INTO Sheet1 (--_==========================================) VALUES 
('-- База данных: Онлайн-курсы'),
('-- СУБД: PostgreSQL'),
('-- =========================================='),
('-- 0. Сброс существующих таблиц (для воспроизводимости)'),
('DROP TABLE IF EXISTS reviews CASCADE;'),
('DROP TABLE IF EXISTS enrollments CASCADE;'),
('DROP TABLE IF EXISTS lessons CASCADE;'),
('DROP TABLE IF EXISTS courses CASCADE;'),
('DROP TABLE IF EXISTS users CASCADE;'),
('-- =========================================='),
('-- 1. Таблица пользователей (User)'),
('-- =========================================='),
('CREATE TABLE users ('),
('    user_id    SERIAL PRIMARY KEY,'),
('    name       VARCHAR(100) NOT NULL,'),
('    email      VARCHAR(150) UNIQUE,'),
('    password   VARCHAR(255) NOT NULL,'),
('    role       VARCHAR(20)  NOT NULL,'),
('    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP'),
(');'),
('-- =========================================='),
('-- 2. Таблица курсов (Course)'),
('-- =========================================='),
('CREATE TABLE courses ('),
('    course_id     SERIAL PRIMARY KEY,'),
('    title         VARCHAR(200) NOT NULL,'),
('    description   TEXT,'),
('    price         DECIMAL(10,2),'),
('    instructor_id INT          NOT NULL,'),
('    share_percent DECIMAL(5,2),'),
('    is_published  BOOLEAN      DEFAULT FALSE,'),
('    CONSTRAINT fk_courses_instructor FOREIGN KEY (instructor_id) '),
('        REFERENCES users(user_id) ON DELETE RESTRICT ON UPDATE CASCADE'),
(');'),
('CREATE INDEX idx_courses_instructor_id ON courses(instructor_id);'),
('-- =========================================='),
('-- 3. Таблица уроков (Lesson)'),
('-- =========================================='),
('CREATE TABLE lessons ('),
('    lesson_id        SERIAL PRIMARY KEY,'),
('    course_id        INT          NOT NULL,'),
('    title            VARCHAR(200) NOT NULL,'),
('    content          TEXT,'),
('    lesson_order     INT,'),
('    duration_minutes INT,'),
('    CONSTRAINT fk_lessons_course FOREIGN KEY (course_id) '),
('        REFERENCES courses(course_id) ON DELETE CASCADE ON UPDATE CASCADE'),
(');'),
('CREATE INDEX idx_lessons_course_id ON lessons(course_id);'),
('-- =========================================='),
('-- 4. Таблица записей на курсы (Enrollment)'),
('-- =========================================='),
('CREATE TABLE enrollments ('),
('    enrollment_id SERIAL PRIMARY KEY,'),
('    student_id    INT          NOT NULL,'),
('    course_id     INT          NOT NULL,'),
('    enrolled_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,'),
('    price_paid    DECIMAL(10,2),'),
('    completed_at  TIMESTAMP,'),
('    CONSTRAINT fk_enrollments_student FOREIGN KEY (student_id) '),
('        REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,'),
('    CONSTRAINT fk_enrollments_course FOREIGN KEY (course_id) '),
('        REFERENCES courses(course_id) ON DELETE CASCADE ON UPDATE CASCADE,'),
('    CONSTRAINT uq_enrollment_student_course UNIQUE (student_id, course_id)'),
(');'),
('CREATE INDEX idx_enrollments_student_id ON enrollments(student_id);'),
('CREATE INDEX idx_enrollments_course_id ON enrollments(course_id);'),
('-- =========================================='),
('-- 5. Таблица отзывов (Review)'),
('-- =========================================='),
('CREATE TABLE reviews ('),
('    review_id   SERIAL PRIMARY KEY,'),
('    course_id   INT          NOT NULL,'),
('    student_id  INT          NOT NULL,'),
('    rating      INT          CHECK (rating >= 1 AND rating <= 5),'),
('    review_text TEXT,'),
('    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,'),
('    CONSTRAINT fk_reviews_course FOREIGN KEY (course_id) '),
('        REFERENCES courses(course_id) ON DELETE CASCADE ON UPDATE CASCADE,'),
('    CONSTRAINT fk_reviews_student FOREIGN KEY (student_id) '),
('        REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,'),
('    CONSTRAINT uq_review_course_student UNIQUE (course_id, student_id)'),
(');'),
('CREATE INDEX idx_reviews_course_id ON reviews(course_id);'),
('CREATE INDEX idx_reviews_student_id ON reviews(student_id);');